### PR TITLE
fix #65

### LINKED ISSUE #65: Bad parameter in error message
Hi,

[This error message](https://github.com/cozy/cozy-db/blob/145790c7df430dcb32ea14dadb157d6486cc4ae5/src/utils/type_checking.coffee#L113) does not output the expected sentence, I think.

At least, in Konnectors, when using the dev tools, I get a lot of

> warn - Cozy DB | Warning : cast ignored property 'fetch' on 'ClassFromGetModel'

which is ok, except that I would have expected an actual model name rather than "ClassFromGetModel".

cc @ZeHiro

### PR DESCRIPTION
**Pull request by ZeHiro**
The change could also be docType instead of displayName

### CODE REVIEW

**Comment by nono** [comment]
@aenario can you review this PR please?

**Comment by aenario** [comment]
~~LGTM, but travis is not happy, I am checking why.~~

Well actually, this will not work with models created by extending the cozydb.Model

``` coffee
class MyModel extends cozydb.Model
```

Could you instead add a test ?

``` coffee
if @name isnt 'ClassFromGetModel' then @name else @displayName
```

**Comment by nono** [comment]
@ZeHiro did you had time to look at this? No worry if it's not the case. It's just a friendly reminder

**Comment by ZeHiro** [comment]
@nono done.

**Pull request merged**
