### PR TITLE
Fixes #15

### LINKED ISSUE #15: .api functions always use the DS, never pouchdb
THis is due to the order of require and the fact that we only know to use pouchdb after the configure, so CozyUser & CozyInstance already extends the CozyBackedModel. Easiest way would probably to override them both in the if (pouchdb) as we do for CozyModel.

### PR DESCRIPTION
**Pull request by runvnc**
cozy-labs/emails now starts up (RUN_STANDALONE) without any errors using cozydb instead of the other.  I also built the docker container for cozy but don't know where the files in there are so I haven't actually run the cozydb tests (Seems to be connecting to localhost so I think it needs cozy running).  Maybe it is not too hard for you guys to double check that.  I can later if you want but it will be (Wed afternoon my time) when I get back to setting up/understanding cozy dev env.

### CODE REVIEW

**Comment by runvnc** [comment]
Yes, I did remove it in the next commit.  I don't get what you mean about causing errors before line 114. I had to add those two lines to get cozy-labs/emails to startup without an error.  Will look at it agsin re: noschema

**Comment by aenario** [comment]
Oups, i was commenting in commit instead of PR. 
My apologies.

And yes, I forgot we use the models below. So let's leave it at that.

**Comment by runvnc** [comment]
As you can see I did not have a cozy dev env setup, just tested the cozy-labs/emails startup.  Travis is very convenient though.

I don't see any reason why those small dependencies cannot be included.  Pouchdb/leveldb however may be taking a long time to build though.  Anyway if you guys are sure that can't go in there I can work on those dependencies tonight. Before I go to bed finally I would like Travis to pass.

**Comment by frankrousseau** [comment]
I will perform some tests and see if it works with Emails application and Calendar (another user requested an update).

**Comment by frankrousseau** [comment]
@aenario If you're ok with the PR, I prefer to handle the merge once my tests will be done.

**Comment by aenario** [comment]
The PR is ok for me, except for the problem of adding pouchbd, leveldb & its compilation to all apps installation in a normal cozy. 

However, I cant figure out a good way to do it from cozydb itself. 
In the actual app, we can have pre-start verification and installation. 
May be it's enough to describe it in README & in case of error [there](https://github.com/cozy/cozy-db/blob/485421cc853fbc62b83ce5206539d34ca56189f5/src/index.coffee#L64).  

I will try a few things tonight.

Thanks @runvnc for your help !

**Comment by runvnc** [comment]
@aenario @frankrousseau thanks for accepting that, I know it needs a bit more refinement and testing still.  I had to go to bed though.  Sadly I woke up again only four or five hours later heh.  I will work on the dev workflow re: actually running tests in the docker container.
The way this works as far as installing pouchdb etc separate intersects with the operation of ' cozy-light install' does it not?

There is probably a more specific place for this but my whole strategy right now for adapting cozy-light apps for Serious Mumbo without having to maintain a bunch of forks of each app relies on the excellent flexibility in the cozy light apps, plugins, and American plugins.  In fact, I was hoping to add one more type of plugin.  If I can add a line of code in Americano  to require my dynplug module then that module can read a list of plugins or plugin modifications from a file which my cozy-light plugin can write to modify the apps that we use.  This dynplug module could even run an npm install before the require if necessary.

**Comment by aenario** [comment]
@runvnc, yep we decided no to include pouchdb with cozydb

We are problaby going to add a small shell script in each app package.json to check & install it if needed (cozy-light or standalone)

**Comment by frankrousseau** [comment]
@runvnc We are still working on cozydb to make emails runnable (current state is broken).

**Comment by runvnc** [comment]
Ok, in my testing the cozy-labs/emails app was loading without errors.  I did not have to chance to test again after making Travis pass for cozy though, and I never actually tried loading emails.

@frankrousseau What part is broken? If you removed those dependencies, it will not start of course.  If you want I can continue (with npm run-script install-standalone or whatever) if I can sync up.   Or I can just continue with the Serious Mumbo integration.

You said something about de-emphasizing plugins before.  You are not getting rid of cozy-light plugins are you?

**Comment by frankrousseau** [comment]
What I mean by testing: importing a full mailbox in the email application. So currently we make manual  tests until we are able to import a full Gmail account in the client. 

@aenario fixed everything yesterday. There were a lot of bugs with cozydb. I still have to fork `cozydb` include the PouchDB dependency and publish this version. Then I will update the cozy-emails fork. Once done you will be able to use it. And @aenario will have more time to think about how to make the process simpler.

About plugins. Cozy Emails has its own plugin system allowing developers to add feature to the client part of the application. We disabled this option because our developers have hard time to improve the client and maintain the plugins at the same time. To go faster on the email client by focusing better, we decided to disable this feature until we reach a satisfying level of usability for the email client.

I hope it makes things clearer. Feel free to ask more questions if needed !

**Pull request merged**
