### PR TITLE
Indexer2

### PR DESCRIPTION
**Pull request by aenario**
This add cozydb methods to declare full-text indexes with the new DS. 
## Note :

Contrary to mapreduceviews, which are defined in server/models/requests.coffee file, the full text indexes are declared inside each model like so.

``` coffee
class MyModel extends CozyModel
     @docType: 'foo'
     @schema: 
           "bar": String
     @fullTextIndexes: 
           "bar": nGramLength: 1, stemming: true, weight: 5, fieldedSearch: true
```

Moreover, we declare the indexes for _ALL_ models in `server/models/*` regardless of their appearance in the `server/models/requests` file. 

I think we should do the same for mapreduce views. Ref : https://github.com/cozy/cozy-db/issues/50

### CODE REVIEW

**Comment by frankrousseau** [comment]
> I think we should do the same for mapreduce views. Ref : #50

That's a good idea @aenario.

**Comment by aenario** [comment]
I fixed your two comments in https://github.com/cozy/cozy-db/commit/df413737fe3b7a0bda2a866ac42abaf17a80df9e

**Comment by frankrousseau** [comment]
Great, thank you @aenario

**Comment by frankrousseau** [comment]
Published as 0.1.4

**Pull request merged**
