### PR TITLE
Add dependencies in package.json

### PR DESCRIPTION
**Pull request by bnjbvr**
I've tested the standalone version of Kresus with these versions, and it seems to work fine. Either way, I'd really like the packages to be in this package.json, whatever the version be :)

@aenario or @frankrousseau, mind to take a look, please?

### CODE REVIEW

**Comment by aenario** [comment]
Well, I have no problem with adding async, however pouchdb is a heavy dependency which needs compiling, so including it by default will increase application installation time in a full cozy and may cause problems in some distrib...

I liked the current state of "if you want your application to be standalone, you need to install pouchdb at application level". 

Alternatively, we could provide a npm script in cozydb, which detect installation and install it.
So, we'd have

``` json
# kresus/package.json
{
  "scripts": {
     "standalone":"npm run cozydb prepare-standalone && RUN_STANDALONE=1 npm start" 
}
```

You can then tell your users to use `npm run standalone` in order to start kresus as a standalone app...

**Comment by bnjbvr** [comment]
How much installation time are we talking about? (relatively to the total installation? time, which is pretty high anyways, as far as i remember)
In most cases, it'd be installed once and then retrieved from the npm cache, so install time shouuld be marginally affected. And it sounds like a bad practice to not declare all dependencies in your package anyway...

**Comment by frankrousseau** [comment]
There is the package cozy-db-pouchdb for that.

**Comment by bnjbvr** [comment]
I thought the two packages were supposed to be merged?

**Comment by frankrousseau** [comment]
Ok thank you. One last thing, could you remove the `^` from the version number. It led us to bad surprises. That's why we prefer strict version numbers.

**Pull request merged**
