### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nono**
Update request-json-light to fix incompatibilities with node 0.12

See https://github.com/cozy/cozy-files/issues/363

### CODE REVIEW

**Comment by aenario** [comment]
It appears the tests are now broken for 0.10 & 0.12, could you investigate ?

**Comment by nono** [comment]
@aenario the tests were already red on master: https://travis-ci.org/cozy/cozy/cozy-db/jobs/82233576#L423. It looks like a race condition.

**Comment by nono** [comment]
@aenario it's green :smile:

**Comment by aenario** [comment]
Thanks ! Released @0.1.1

**Pull request merged**
